version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/node'
