version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint-plugin-vitest"
        update-types:
          - "version-update:semver-minor"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
