name: publish
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release

  publish:
    if: ${{ needs.release.outputs.release_created }}
    needs: [release]
    runs-on: ubuntu-latest
    environment:
      name: NPM
      url: https://www.npmjs.com/package/esbuild-plugin-browserslist/v/${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # waiting on: https://github.com/actions/setup-node/issues/531
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      # needed for type-aware linting (part of prepublishOnly) to work
      - name: install package-test
        working-directory: ./package-test/
        run: |
          pnpm install --frozen-lockfile
      - run: pnpm publish --access public
